language: csharp
solution: MagisIT.ReactiveActions.sln
dist: xenial
mono: none
dotnet: 2.2

services:
  - redis-server

install:
  - dotnet restore

script:
  - dotnet test
  - dotnet build -c Release

deploy:
  provider: script
  script: dotnet pack MagisIT.ReactiveActions/MagisIT.ReactiveActions.csproj -c Release && \
    dotnet pack MagisIT.ReactiveActions.TrackingSessionStore.InMemoroy/MagisIT.ReactiveActions.TrackingSessionStore.InMemoroy.csproj -c Release && \
    dotnet pack MagisIT.ReactiveActions.TrackingSessionStore.Redis/MagisIT.ReactiveActions.TrackingSessionStore.Redis.csproj -c Release && \
    find . -name '*.nupkg' -exec dotnet nuget push {} -k $NUGET_KEY -s https://nuget.org \;
  on:
    tags: true
